### ISSUE TITLE
Having an issue running the run_human_game.py

### ISSUE THREAD

**Issue by dberweger2017** [piteren/pypoks#15]
Encountered an issue where running the run_human_game.py couldn't find envy.py. So I'm running it as a module "python -m run.run_human_game"

Now getting this error:

```python 
(poker) PS C:\Users\dberw\Desktop\pypoks\pypoks> python -m run.run_human_game
2024-09-12 18:49:22,469 {   run_human_game.py:  18} p16492 INFO: Human Game starts
2024-09-12 18:49:22,472 {   run_human_game.py:  25} p16492 INFO: > 3 table players
2024-09-12 18:49:22,472 {   run_human_game.py:  31} p16492 INFO: got players from loop results: ['dmk073a00', 'dmk136a01']
2024-09-12 18:49:22,472 {     game_manager.py: 133} p16492 INFO: *** HumanGameManager : HumanGameManager *** starts..
2024-09-12 18:49:22,474 {              dmk.py:  71} p16492 INFO: *** HumanDMK (DMK) : human *** initialized
2024-09-12 18:49:22,475 {              dmk.py:  71} p16492 INFO: *** FolDMK (DMK) : dmk073a00 *** initialized
2024-09-12 18:49:22,476 {              dmk.py:  71} p16492 INFO: *** FolDMK (DMK) : dmk136a01 *** initialized
2024-09-12 18:49:22,477 {   human_game_gui.py:  55} p16492 INFO: *** HumanGameGUI *** starts with players: ['human', 'dmk073a00', 'dmk136a01']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dberw\Desktop\pypoks\pypoks\run\run_human_game.py", line 51, in <module>
    gm.start_game()
  File "C:\Users\dberw\Desktop\pypoks\pypoks\podecide\game_manager.py", line 782, in start_game
    self.start_gui()
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\site-packages\pypaq\mpython\mpdecor.py", line 11, in new_f
    p.start()
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function HumanGameManager.start_gui at 0x0000015617195DA0>: it's not the same object as podecide.game_manager.HumanGameManager.start_gui
(poker) PS C:\Users\dberw\Desktop\pypoks\pypoks> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dberw\miniconda3\envs\poker\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
```
The problem being:
```python 
_pickle.PicklingError: Can't pickle <function HumanGameManager.start_gui at 0x0000015617195DA0>: it's not the same object as podecide.game_manager.HumanGameManager.start_gui
```

The issue seems to be in the proc decorator. Running the code without it no problem but the GUI is obviously frozen since I'm blocking the main thread.

Also tried to run like this but still didn't work:

```python 
Import threading

def start_gui(self):
    # Run the GUI loop in a separate thread
    gui_thread = threading.Thread(target=self.gui.run_loop)
    gui_thread.start()
    self.logger.debug('GUI started in separate thread')
```

Thanks in advance for any help.

**Comment by Adrien2112** [comment]
hello @dberweger2017 , how did you solve the issue ?
